server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhist:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
       mode: always

build:
  version: "3.0"
