server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhist:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
       mode: always

build:
  version: "3.7"
